# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Espresso Build-Docker image

on:
  push:
    branches: [main, ci, hotshot-integration]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: NPM Install
        run: npm install

      - name: Build contracts docker
        run: npm run docker:contracts

      # Steps to push multi-platform image, it relies on the previous step:
      #  npm run docker:contracts
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker metadata
        uses: docker/metadata-action@v4
        id: geth-zkevm-contracts
        with:
          images: ghcr.io/${{ github.repository_owner }}/geth-zkevm-contracts

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.geth-zkevm-contracts.outputs.tags }}
          labels: ${{ steps.geth-zkevm-contracts.outputs.labels }}
          file: docker/Dockerfile.geth
          context: .
